apiVersion: v1
kind: Secret
metadata:
    name: pocket-id-secrets
    namespace: identity
stringData:
    encryptionKey: ENC[AES256_GCM,data:PJajCj1ljfNxje2Otd/2xPLsPItS0grtTe+ApdGrS3f7oDdQXSjZ9o0wMkc=,iv:w8Sb5/CYUPojLXvrh7eVzU6sMNTTuasiabrYzzxXXQg=,tag:F238nngUbipWdcA3M9j46A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPTDhGRTZZancxMnBMK0dr
            UnhKYllnd3dINkt6N0FUV2swMGpEMkdvM0M0Cis4eUlrSHpmeUVqeUtmR2czaTdm
            ZnNwbHZwcTJpMURwYWwvV09YVlhvRm8KLS0tIDZKNzR2TElHVTFHZXZjQ2ZrQXFG
            T2xPT09BbWx2VldWbUlxUFhPWDlRSGsKUwImcR/sdkemUpzpzblFP1BOmgu49sfA
            E402WadjZxMJ2NP2guqwcBAlS1YcgsfAe+YdBPZ7cmgLEjpWRNP/Gw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age18txq486alpfcfq4eqldkarzc0n4p49znr3ehmws35vwtjx84pu0szq4gt8
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-30T21:43:18Z"
    mac: ENC[AES256_GCM,data:QS7qkIzHb0Jq3o1ico+B35JyKpf965czBeyvNgsaN2HuzJ22G2ekDNIPnyTDJ1XSrkAMPor2D8DFvU0cdnQCQuv08B+UpiUlMkLLEiGRd43GVqqqp6LghB7cxy7RhRV4kjVbzx5gcLwf8TGHJlFyQ0XH2FvMVJz+L/KV/0Rm7GQ=,iv:7f18JEf/bfCjVuFTCIuUJVeDbFW+dk943F2WKepKrDQ=,tag:zzYA8ffl47fgG9CSiIM8VA==,type:str]
    version: 3.13.3
