apiVersion: v1
kind: Service
metadata:
  name: talos-api
  namespace: tailscale-operator
  annotations:
    tailscale.com/hostname: talos-api
    tailscale.com/tags: "tag:talos-api"
spec:
  type: LoadBalancer
  loadBalancerClass: tailscale
  ports:
    - name: talos-grpc
      port: 50000
      targetPort: 50000
      protocol: TCP
