apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/cnpg-operator
  - ../base/traefik
  - ../base/tailscale-operator
  - operator-oauth.sops.yaml
  - talos-api-endpoints.yaml
patches:
  - path: traefik-values-patch.yaml
    target:
      kind: HelmRelease
      name: traefik
  - path: tailscale-patch.yaml
    target:
      kind: HelmRelease
      name: tailscale-operator
  - path: talos-api-service-patch.yaml
    target:
      kind: Service
      name: talos-api
