apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale-operator
  namespace: tailscale-operator
spec:
  values:
    operatorConfig:
      hostname: tailscale-operator-tierhive
