apiVersion: v1
kind: Secret
metadata:
    name: pocket-id-secrets
    namespace: identity
stringData:
    encryptionKey: ENC[AES256_GCM,data:oYvsyvAi2jna5xqTvNpgpcEuTdo0kexCJbImpsndU1IkQ2jlEMCVfFw3oKU=,iv:eqeTEGTA6z42hcKCO4wOpJ+pE5lyJU9uoejv6ToRY64=,tag:SRWgBljTo33OyQdhx/bUog==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1Yy9SVzBubU0vOEU2aldY
            WWdRYjNqb2wyNmU2YXpnR1lZUi9FNTFVbFd3CmhxRDVvdVdJUGNOc2g1VTRVQmln
            bExGbFRGNnUycXpXUjFidXBBSzg2WUEKLS0tIEQ3b3A4NjdWNUVOaXBIamF2alBQ
            ZzZmc3NxUUk2VWZ2ZUdmYWV4eTczd3cK5miZI6TGK5KNhutufT4MxcrtiBVhGLn3
            /CTsBLM1z7v/BNFIQL/A/4EpzFh9z8L0ndXqYW8akS1GMdzKpND40w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nl9yjkq033pufe0hc50fn3z5xrup356cne34p7mezg5m9slt440sawk002
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-15T19:36:42Z"
    mac: ENC[AES256_GCM,data:8t7qeuRBmw8g7Mv3pCmdBwDMUxReGKTXG3x2yKCrLeuFweiD8ZFObdB12g5t5IpWzxU4JGsqOrf1NCo0tLIVRDZJLUZ0d2L2rHcQNNNbe3w9eguGUke2s3huTdXmGotcd9QEoPN1Jl8R4FOcRALqYgdp1x4WwKdAuLUIubl29AE=,iv:H08yObrop529YW7RdhxaPziXfd218cPPjS0+DJPGVYA=,tag:Rw9+vEkBsoeMvoD4QrOQlg==,type:str]
    version: 3.13.3
