apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
  namespace: immich
spec:
  values:
    server:
      persistence:
        home-lab-ca-cert:
          type: configMap
          name: home-lab-ca-cert
          globalMounts:
            - path: /usr/local/share/ca-certificates/home-lab-ca.crt
              subPath: ca.crt
              readOnly: true
      controllers:
        main:
          containers:
            main:
              env:
                NODE_EXTRA_CA_CERTS: /usr/local/share/ca-certificates/home-lab-ca.crt
      ingress:
        main:
          enabled: true
          className: traefik
          annotations:
            cert-manager.io/cluster-issuer: ca-issuer
          hosts:
            - host: immich.home.arpa
              paths:
                - path: "/"
                  service:
                    identifier: main
          tls:
            - hosts:
                - immich.home.arpa
              secretName: immich-tls
